### ISSUE TITLE
Create Game Manager

### ISSUE THREAD

**Issue by Victorma** [Victormafire/TinyWorld#3]
En la clase:
https://github.com/Victormafire/TinyWorld/blob/master/Server/Icaro/src/icaro/aplicaciones/recursos/comunicacionChat/imp/InterpreteMsgsUnity.java

/src/icaro/aplicaciones/recursos/comunicacionChat/imp/InterpreteMsgsUnity, en la función onPrivateMessage() se debe identificar el usuario del evento, y si no hay un game manager con ese usuario, se creará uno nuevo.

**Comment by juzaru18** [comment]
Creación de un agente que se encargue de gestionar el estado del juego por usuario. Este Agente instanciará los muñecos, su vida, comprobar el estado de los objetivos, los agentes enviarán los objetivos que van cumpliendo a este agente y cuando se cumplan todos habrá ganado la partida y cerrará las instancias de los agentes creados. Se creará una clase que almacene loa info de la partida iniciada, cuantos minions existen, la vida que tienen,  si se han cumplido los objetivos, en caso de cierto indica mensaje de ganador, en caso fin de tiempo o de vida indica mensaje de perdedor.

**Comment by Victorma** [comment]
Ahora que he leído esto, no es aquí donde tienes que ponerlos.
Edita la milestone si quieres y escríbelo ahí. El caso es que tienes que crear nuevas Issues para cada objetivo. En cada issue pones lo que vayas a necesitar y el diagrama que explique su ciclo de consecución.
Esta issue está orientada a decir, dónde se debe crear el Game manager. No es un objetivo del agente, es la issue encargada de darle vida.

**Comment by Victorma** [comment]
![agente gestor](https://cloud.githubusercontent.com/assets/3171485/7308080/7baa1a4c-ea11-11e4-9233-afc170c4ef2d.png)
